/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : ClientId,
  'name' : string,
  'notes' : [] | [string],
}
export type ClientId = bigint;
export interface CreateClientDto { 'name' : string, 'notes' : [] | [string] }
export interface CreateLogEntryDto {
  'weight' : number,
  'height' : number,
  'clientId' : ClientId,
  'stepsDaily' : bigint,
  'hipCm' : number,
  'proteinIntake' : number,
  'calorieIntake' : number,
  'waterIntake' : number,
  'date' : Time,
  'attendance' : boolean,
  'cardioDuration' : number,
  'dietPercent' : number,
  'workoutsToday' : string,
  'waistCm' : number,
  'sleepHours' : number,
}
export interface LogEntry {
  'id' : LogEntryId,
  'weight' : number,
  'height' : number,
  'clientId' : ClientId,
  'stepsDaily' : bigint,
  'hipCm' : number,
  'proteinIntake' : number,
  'calorieIntake' : number,
  'waterIntake' : number,
  'date' : Time,
  'attendance' : boolean,
  'cardioDuration' : number,
  'dietPercent' : number,
  'workoutsToday' : string,
  'waistCm' : number,
  'sleepHours' : number,
}
export type LogEntryId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLogEntry' : ActorMethod<[CreateLogEntryDto], LogEntryId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<[CreateClientDto], ClientId>,
  'deleteClient' : ActorMethod<[ClientId], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[ClientId], Client>,
  'getLogEntriesForClient' : ActorMethod<[ClientId], Array<LogEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'verifyTrainerPin' : ActorMethod<[string], boolean>,
  'updateTrainerPin' : ActorMethod<[string], undefined>,
  'setClientPin' : ActorMethod<[ClientId, string], undefined>,
  'removeClientPin' : ActorMethod<[ClientId], undefined>,
  'lookupClientByPin' : ActorMethod<[string], [] | [ClientId]>,
  'getClientPin' : ActorMethod<[ClientId], [] | [string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
