/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateLogEntryDto {
    weight: number;
    height: number;
    clientId: ClientId;
    stepsDaily: bigint;
    hipCm: number;
    proteinIntake: number;
    calorieIntake: number;
    waterIntake: number;
    date: Time;
    attendance: boolean;
    cardioDuration: number;
    dietPercent: number;
    workoutsToday: string;
    waistCm: number;
    sleepHours: number;
}
export type Time = bigint;
export interface LogEntry {
    id: LogEntryId;
    weight: number;
    height: number;
    clientId: ClientId;
    stepsDaily: bigint;
    hipCm: number;
    proteinIntake: number;
    calorieIntake: number;
    waterIntake: number;
    date: Time;
    attendance: boolean;
    cardioDuration: number;
    dietPercent: number;
    workoutsToday: string;
    waistCm: number;
    sleepHours: number;
}
export interface CreateClientDto {
    name: string;
    notes?: string;
}
export interface Client {
    id: ClientId;
    name: string;
    notes?: string;
}
export type LogEntryId = bigint;
export interface UserProfile {
    name: string;
}
export type ClientId = bigint;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLogEntry(dto: CreateLogEntryDto): Promise<LogEntryId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClient(dto: CreateClientDto): Promise<ClientId>;
    deleteClient(clientId: ClientId): Promise<void>;
    getAllClients(): Promise<Array<Client>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(id: ClientId): Promise<Client>;
    getLogEntriesForClient(clientId: ClientId): Promise<Array<LogEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    verifyTrainerPin(pin: string): Promise<boolean>;
    updateTrainerPin(pin: string): Promise<void>;
    setClientPin(clientId: ClientId, pin: string): Promise<void>;
    removeClientPin(clientId: ClientId): Promise<void>;
    lookupClientByPin(pin: string): Promise<ClientId | null>;
    getClientPin(clientId: ClientId): Promise<string | null>;
}
import type { Client as _Client, ClientId as _ClientId, CreateClientDto as _CreateClientDto, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLogEntry(arg0: CreateLogEntryDto): Promise<LogEntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addLogEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLogEntry(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClient(arg0: CreateClientDto): Promise<ClientId> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(to_candid_CreateClientDto_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(to_candid_CreateClientDto_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteClient(arg0: ClientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: ClientId): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_Client_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_Client_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogEntriesForClient(arg0: ClientId): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogEntriesForClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogEntriesForClient(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async verifyTrainerPin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try { return await this.actor.verifyTrainerPin(arg0); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        }
        return await this.actor.verifyTrainerPin(arg0);
    }
    async updateTrainerPin(arg0: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.updateTrainerPin(arg0); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        }
        return await this.actor.updateTrainerPin(arg0);
    }
    async setClientPin(arg0: ClientId, arg1: string): Promise<void> {
        if (this.processError) {
            try { return await this.actor.setClientPin(arg0, arg1); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        }
        return await this.actor.setClientPin(arg0, arg1);
    }
    async removeClientPin(arg0: ClientId): Promise<void> {
        if (this.processError) {
            try { return await this.actor.removeClientPin(arg0); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        }
        return await this.actor.removeClientPin(arg0);
    }
    async lookupClientByPin(arg0: string): Promise<ClientId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupClientByPin(arg0);
                return result.length === 0 ? null : result[0];
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        }
        const result = await this.actor.lookupClientByPin(arg0);
        return result.length === 0 ? null : result[0];
    }
    async getClientPin(arg0: ClientId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientPin(arg0);
                return result.length === 0 ? null : result[0];
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        }
        const result = await this.actor.getClientPin(arg0);
        return result.length === 0 ? null : result[0];
    }
}
function from_candid_Client_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClientId;
    name: string;
    notes: [] | [string];
}): {
    id: ClientId;
    name: string;
    notes?: string;
} {
    return {
        id: value.id,
        name: value.name,
        notes: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CreateClientDto_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateClientDto): _CreateClientDto {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    notes?: string;
}): {
    name: string;
    notes: [] | [string];
} {
    return {
        name: value.name,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
